### ISSUE TITLE
Start with and only at the same time

### ISSUE THREAD

**Issue by pablodip** [tolitius/yurt#6]
I am trying to build a Yurt with only certain states, and with certain of those states modified. But I haven't seen a function that combines both `start-only` and `start-with`.

So how could that be done? Is it a limitation or something I couldn't just find?

Thanks a lot! :)

**Comment by tolitius** [comment]
thanks for the question since I simply forgot to include this in docs.

which I did now, and you can certainly do it via [building Yurts declaratively](https://github.com/tolitius/yurt#declarative-yurts).

Let me know if that helps.

**Comment by pablodip** [comment]
Sure it helps.

For some reason I got downloaded [this version](https://github.com/tolitius/yurt/commit/88268f8616767b256c3229df31909c172f83fe36#diff-3f69f4fb13d7d1dce04535c5fd49aec3) of Yurt even if I set `0.1.1`, that's why I didn't understand the docs at first, since in that version `build` didn't have any options.

Closing the issue then.

Thanks! :)
