### ISSUE TITLE
Release of 0.1.2?

### ISSUE THREAD

**Issue by coreagile** [tolitius/yurt#9]
Greetings,

There is functionality mentioned in the project's README that can't be used by the current published release (namely, the ability to do both a `:swap` and `:only` in a single yurt construction). In order to get access to the functionality I needed to fork the project and deploy my own version to clojars.

Is there any chance we can get the latest master code published?

Thanks!

**Comment by tolitius** [comment]
I apologize, I missed this issue.

the latest master is released: `[yurt "0.1.2"]` (in clojars)
